sudo: false
language: node_js
node_js: lts/*
dist: trusty
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  bundler: true
  pip: true
  npm: true
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry npm ci --legacy-peer-deps
- travis_retry cypress install
script:
- npm run build
- npm run test:coverage -- --runInBand
- npm run start &
- wait-on http://localhost:8080
- $(npm bin)/cypress run --config video=false
after_success:
- ./s3_deploy.sh
